export type Database = {
  public: {
    Tables: {
      companies: {
        Row: {
          id: number
          name: string
          code: string
          contact_person?: string
          phone?: string
          email?: string
          address?: string
          city?: string
          state?: string
          country?: string
          postal_code?: string
          tax_id?: string
          license_number?: string
          subscription_plan?: string
          subscription_expires?: string
          is_active?: boolean
          logo_filename?: string
          created_at?: string
          updated_at?: string
        }
        Insert: {
          id?: number
          name: string
          code: string
          contact_person?: string
          phone?: string
          email?: string
          address?: string
          city?: string
          state?: string
          country?: string
          postal_code?: string
          tax_id?: string
          license_number?: string
          subscription_plan?: string
          subscription_expires?: string
          is_active?: boolean
          logo_filename?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          name?: string
          code?: string
          contact_person?: string
          phone?: string
          email?: string
          address?: string
          city?: string
          state?: string
          country?: string
          postal_code?: string
          tax_id?: string
          license_number?: string
          subscription_plan?: string
          subscription_expires?: string
          is_active?: boolean
          logo_filename?: string
          created_at?: string
          updated_at?: string
        }
      }
      users: {
        Row: {
          id: number
          auth_user_id?: string
          username: string
          email: string
          first_name: string
          last_name: string
          phone?: string
          is_active?: boolean
          is_super_admin?: boolean
          role?: string
          company_id?: number
          last_login?: string
          created_at?: string
          updated_at?: string
        }
        Insert: {
          id?: number
          auth_user_id?: string
          username: string
          email: string
          first_name: string
          last_name: string
          phone?: string
          is_active?: boolean
          is_super_admin?: boolean
          role?: string
          company_id?: number
          last_login?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          auth_user_id?: string
          username?: string
          email?: string
          first_name?: string
          last_name?: string
          phone?: string
          is_active?: boolean
          is_super_admin?: boolean
          role?: string
          company_id?: number
          last_login?: string
          created_at?: string
          updated_at?: string
        }
      }
      clients: {
        Row: {
          id: number
          name: string
          email?: string
          phone?: string
          address?: string
          city?: string
          state?: string
          country?: string
          postal_code?: string
          tax_id?: string
          contact_person?: string
          credit_limit?: number
          payment_terms?: string
          is_active?: boolean
          company_id: number
          created_at?: string
          updated_at?: string
        }
        Insert: {
          id?: number
          name: string
          email?: string
          phone?: string
          address?: string
          city?: string
          state?: string
          country?: string
          postal_code?: string
          tax_id?: string
          contact_person?: string
          credit_limit?: number
          payment_terms?: string
          is_active?: boolean
          company_id: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          name?: string
          email?: string
          phone?: string
          address?: string
          city?: string
          state?: string
          country?: string
          postal_code?: string
          tax_id?: string
          contact_person?: string
          credit_limit?: number
          payment_terms?: string
          is_active?: boolean
          company_id?: number
          created_at?: string
          updated_at?: string
        }
      }
      vehicles: {
        Row: {
          id: number
          registration_number: string
          vehicle_type: string
          make?: string
          model?: string
          year?: number
          capacity?: number
          driver_name?: string
          driver_phone?: string
          driver_license?: string
          insurance_number?: string
          insurance_expiry?: string
          fitness_expiry?: string
          permit_expiry?: string
          is_active?: boolean
          company_id: number
          created_at?: string
          updated_at?: string
        }
        Insert: {
          id?: number
          registration_number: string
          vehicle_type: string
          make?: string
          model?: string
          year?: number
          capacity?: number
          driver_name?: string
          driver_phone?: string
          driver_license?: string
          insurance_number?: string
          insurance_expiry?: string
          fitness_expiry?: string
          permit_expiry?: string
          is_active?: boolean
          company_id: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          registration_number?: string
          vehicle_type?: string
          make?: string
          model?: string
          year?: number
          capacity?: number
          driver_name?: string
          driver_phone?: string
          driver_license?: string
          insurance_number?: string
          insurance_expiry?: string
          fitness_expiry?: string
          permit_expiry?: string
          is_active?: boolean
          company_id?: number
          created_at?: string
          updated_at?: string
        }
      }
      invoices: {
        Row: {
          id: number
          invoice_number: string
          client_id: number
          invoice_date: string
          due_date: string
          subtotal: number
          tax_amount: number
          total_amount: number
          status?: string
          notes?: string
          company_id: number
          created_at?: string
          updated_at?: string
        }
        Insert: {
          id?: number
          invoice_number: string
          client_id: number
          invoice_date: string
          due_date: string
          subtotal?: number
          tax_amount?: number
          total_amount: number
          status?: string
          notes?: string
          company_id: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          invoice_number?: string
          client_id?: number
          invoice_date?: string
          due_date?: string
          subtotal?: number
          tax_amount?: number
          total_amount?: number
          status?: string
          notes?: string
          company_id?: number
          created_at?: string
          updated_at?: string
        }
      }
      transactions: {
        Row: {
          id: number
          transaction_number: string
          client_id: number
          vehicle_id?: number
          from_location: string
          to_location: string
          goods_description?: string
          weight?: number
          freight_amount?: number
          advance_amount?: number
          balance_amount?: number
          status?: string
          pickup_date?: string
          delivery_date?: string
          actual_delivery_date?: string
          company_id: number
          created_at?: string
          updated_at?: string
        }
        Insert: {
          id?: number
          transaction_number: string
          client_id: number
          vehicle_id?: number
          from_location: string
          to_location: string
          goods_description?: string
          weight?: number
          freight_amount?: number
          advance_amount?: number
          balance_amount?: number
          status?: string
          pickup_date?: string
          delivery_date?: string
          actual_delivery_date?: string
          company_id: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          transaction_number?: string
          client_id?: number
          vehicle_id?: number
          from_location?: string
          to_location?: string
          goods_description?: string
          weight?: number
          freight_amount?: number
          advance_amount?: number
          balance_amount?: number
          status?: string
          pickup_date?: string
          delivery_date?: string
          actual_delivery_date?: string
          company_id?: number
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}